language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11  # Python 3.7 running on macOS 10.14
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  allow_failures:
    - os: linux
install:
# - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
- pip3 install --upgrade wxPython || pip3 install --upgrade wxPython
- pip3 install -r requirements.txt || pip3 install -r requirements.txt
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: sh bundledApps/MAKEFILE.sh ci
# script: pytest